# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rvMF64 <- function(n, p, kappa, log_const) {
    .Call(`_rvMF_rvMF64`, n, p, kappa, log_const)
}

